export const CONFIG = {
  BUSINESS_HOURS: { start: 10, end: 16 },
  SLOT_DURATION_MINUTES: 60,
  TIMEZONE: "Asia/Tokyo",
  CANCEL_DEADLINE_HOURS: 24,
  BOOKING_DEADLINE_HOURS: 2,
  BOOKING_WINDOW_DAYS: 30,
  BUFFER_MINUTES: 0,
  ACCESS_TOKEN_VALID_BEFORE_HOURS: 48,
} as const;
